[package]
name = "meme_spike"
version = "1.0.0"
authors = []

[addresses]

spike = "0xfec116479f1fd3cb9732cc768e6061b0e45b178a610b9bc23c2143a6493e794"

[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "1e65b4020f72ccb40a83561ace5fd59dfa31d5e4"
subdir = "aptos-move/framework/supra-framework"


[dev-dependencies]
